version: "3"
services:
  url:
    # TODO: Publish to docker hub
    build:
      context: .
    container_name: url
    ports:
      - 4567:4567
    environment:
      - file.location=/urls.csv
      - username=admin
      - password=admin
    volumes:
      - ./urls.csv:/urls.csv